const data = [
  {
    title: "Café Amargo",
    artist: "Supercombo",
    src: "../../img/supercombo-cafeamargo.png",
    lyrics: [
     "Ohhh, I got the midterm blues,",
      "Sleep-deprived and confused.",
      "One more shock and I’ll short-circuit,",
      "Maybe I should switch to business—nah, I ain’t worth it.",
    ],
    theme: [
      {
        primaryColor: "#A9800A",
        secondaryColor: "#F6F6F4",
      },
      {
        primaryColor: "#392C02",
        secondaryColor: "#9D7C13",
      },
      {
        primaryColor: "#EEEEEE",
        secondaryColor: "#010101",
      },
    ],
  },
  {
    title: "Todo Carinho",
    artist: "Duda Beat",
    src: "\"../../img/dudabeat-todocarinho.jpg\"",
    lyrics: [
        "Beijei ontem à noite",
        "Mas acordei sozinha",
        "Difícil de falar dessas relações",
        "Eu sou de outro tempo",
        "Amor que é pra sempre",
        "E tanto sentimento guardado pra nós dois",
        "Que se eu só tivesse hoje",
        "Pra poder te amar de novo",
        "Beijei ontem à noite",
        "Mas acordei sozinha",
        "Difícil de falar dessas relações",
        "Eu sou de outro tempo",
        "Amor que é pra sempre",
        "E tanto sentimento guardado pra nós dois",
        "Que se eu só tivesse hoje",
        "Pra poder te amar de novo, de novo",
        "Que se eu só tivesse hoje",
        "Pra poder te amar de novo, de novo",
        "É que eu amo você",
        "E eu nem sei porquê",
        "Que eu amo você (ah ah ah)",
        "É que eu amo você",
        "E eu não sei porquê",
        "Que que que eu amo você",
        "De novo",
        "De novo",
        "De novo",
        "De novo",
        "É que eu amo você",
        "E eu não sei porquê",
        "Que eu amo você (ah ah ah)",
        "É, é que eu amo você",
        "E eu não sei porquê",
        "Que eu amo você",
        "De novo",
        "Todo carinho do mundo para mim é pouco",
        "Todo carinho do mundo para mim é pouco",
        "Todo carinho do mundo para mim é pouco",
        "Todo carinho do mundo para mim é pouco",
        "Para mim é pouco",
        "Todo carinho do mundo para mim é pouco",
        "Todo carinho do mundo para mim é pouco",
    ],
    theme: [
      {
        primaryColor: "#C22305",
        secondaryColor: "#F6F6F4",
      },
      {
        primaryColor: "#2E0700",
        secondaryColor: "#A22108",
      },
      {
        primaryColor: "#EEEEEE",
        secondaryColor: "#010101",
      },
    ],
  },
  {
    title: "Amianto",
    artist: "Supercombo",
    src: "../../img/supercombo-amianto.jpg",
    lyrics: [
      "Moça, sai da sacada",
      "Você é muito nova pra brincar de morrer",
      "Me diz o que há,",
      "O quê que a vida aprontou dessa vez?",
      "Venha, desce daí",
      "Deixa eu te levar pra um café, pra conversar",
      "Te ouvir",
      "E tentar te convencer",
      "Que a vida é como mãe",
      "Que faz o jantar e obriga os filhos a comer",
      "Os vegetais, pois sabe que faz bem",
      "E a morte é como um pai",
      "Que bate na mãe e rouba os filhos do prazer",
      "De brincar, como se não houvesse amanhã",
      "Moça, não olha pra baixo",
      "Aí é muito alto",
      "Pra você se jogar",
      "Vou te ouvir",
      "E tentar te convencer",
      "(Somos programados pra cair)",
      "Que a vida é como mãe",
      "Que faz o jantar e obriga os filhos a comer",
      "Os vegetais, pois sabe que faz bem",
      "E a morte é como um pai",
      "Que bate na mãe e rouba os filhos do prazer",
      "De brincar, como se não houvesse amanhã",
      "Mas tudo bem, nem sempre estamos na melhor",
      "Moço, ninguém é de ferro",
      "Somos programados pra cair",
    ],
    theme: [
      {
        primaryColor: "#949549",
        secondaryColor: "#F6F6F4",
      },
      {
        primaryColor: "#323218",
        secondaryColor: "#959648",
      },
      {
        primaryColor: "#EEEEEE",
        secondaryColor: "#010101",
      },
    ],
  },
];

export default data;
